### ISSUE TITLE
How did we get here? "Warnings (1) but it shows empty

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#9] opened 2021-06-25 07:49 UTC
![image](https://user-images.githubusercontent.com/4569581/123389862-9c5db980-d59a-11eb-9658-8cf57bba52df.png)

No clue how this bug happens... But here is a screenshot. 

Happens here and there...

**Comment by vlad-timotei** [comment] 2021-06-25 08:07
I think it has something to do with: „10 translations have been submitted.” Where does that come from? It looks like some async stuff WPGPT doesn't fetch. 

WPGPT hides rows only when you press on
- Notices 
- Warnings

Next time, if you press on all and strings appear, then it's a WPGPT bug. If not... the missing strings are not caused by WPGPT, but the Warnings(1) indeed is not correct. 

Can you reproduce some steps? Did you import strings? Did you fill them with TranslationFiller...? 

Yet another thing to debug 😆

**Comment by NekoJonez** [comment] 2021-06-25 10:26
I haven't TranslationFiller installed anymore...

**Comment by vlad-timotei** [comment] 2021-07-12 04:17
Keep in mind that those counts with icons are only accurate at the first page load. Then, if translations change, it won't update. So my guess here is that some  changes has been made without a page reload and that is a previous count. Closing this for now, but feel free to comment if you have anything new to add to this. Thank you.

**Closed by vlad-timotei** 2021-07-12 04:17 UTC
Labels: question
