### ISSUE TITLE
No reaction when unneeded punction marks are added in suggestions

### ISSUE THREAD

**Issue by NekoJonez** [vlad-timotei/wpgp-tools#10] opened 2021-06-25 12:47 UTC
So, to save some time, I downloaded the complete translation from nl_NL to tweak for nl_BE for the broken link checker plugin. 

Then I noticed this: 

![image](https://user-images.githubusercontent.com/4569581/123426779-1ce4e000-d5c4-11eb-8c0b-84422fd4731d.png)

It seems kinda strange to me that the script can tell you when you are missing a punction mark at the end but when an unneeded one is added, you don't get a warning.

**Comment by vlad-timotei** [comment] 2021-06-28 06:12
![image](https://user-images.githubusercontent.com/65488419/123588673-c7d9e180-d7f0-11eb-9e94-624f647db939.png)
I can't reproduce this issue...
Have you checked WPGPT settings? 
![image](https://user-images.githubusercontent.com/65488419/123588745-e809a080-d7f0-11eb-988f-3f068d2c9ce5.png)

**Comment by NekoJonez** [comment] 2021-06-29 07:56
Heh, it's the exact same... Well, might it have to do with the fact that I imported like 2K-ish strings for a plugin and the tool is lagging when checking?

**Comment by vlad-timotei** [comment] 2021-06-29 08:24
Please provide a string URL where I can see this - original doesn't have ending `:`, translation has ending `:` and there is no warning. I can debug if I see it in action 😁 Thanks.

**Comment by vlad-timotei** [comment] 2021-06-29 08:30
Found it: https://translate.wordpress.org/projects/wp-plugins/broken-link-checker/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=582001&filters%5Btranslation_id%5D=85040439

This one is odd. In preview there is a warning:
![image](https://user-images.githubusercontent.com/65488419/123764206-3f7d3e80-d8cd-11eb-9fb2-df77d235bd92.png)

But in the editor the warning is gone, yet, the Save with warnings checkbox is there... 
![image](https://user-images.githubusercontent.com/65488419/123764330-5ae84980-d8cd-11eb-8b37-e1fa49dbb196.png)

I'll have to check where the bug is exactly. 
Thanks for reporting.

**Comment by vlad-timotei** [comment] 2021-06-29 08:35
Nah, the above bug is not related to what you said. The above thing happens because I don't have action buttons (Approve/Reject) on this locale and `jQuery(this).find('.actions .action.edit').prepend( preview_html_output );` fails. But you should see the list of warnings as PTE.

**Comment by vlad-timotei** [comment] 2021-06-29 09:01
The issue mentioned by me will be fixed in 1.4, but this shouldn't affect you, since you're a PTE for that project, so still need to debug. Here's what I see for this string now:
![image](https://user-images.githubusercontent.com/65488419/123769244-c0d6d000-d8d1-11eb-9202-fffdafc41871.png)

**Comment by NekoJonez** [comment] 2021-06-29 09:02
Nice nice! :D

**Comment by vlad-timotei** [comment] 2021-07-12 04:14
Closing this, but feel free to comment if you can replicate. I couldn't. Maybe it was related to the thing fixed now in 1.4.

**Closed by vlad-timotei** 2021-07-12 04:14 UTC
Labels: question
